import { createContext, useContext, useState, ReactNode } from 'react';

export interface LanguageOption {
  code: string;
  name: string;
  native_name: string;
  voice_available: boolean;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', native_name: 'English', voice_available: true },
  { code: 'te', name: 'Telugu', native_name: 'తెలుగు', voice_available: true },
  { code: 'hi', name: 'Hindi', native_name: 'हिन्दी', voice_available: true },
  { code: 'ta', name: 'Tamil', native_name: 'தமிழ்', voice_available: true },
  { code: 'kn', name: 'Kannada', native_name: 'ಕನ್ನಡ', voice_available: true },
  { code: 'ml', name: 'Malayalam', native_name: 'മലയാളം', voice_available: true },
  { code: 'mr', name: 'Marathi', native_name: 'मराठी', voice_available: true },
  { code: 'gu', name: 'Gujarati', native_name: 'ગુજરાતી', voice_available: true },
  { code: 'bn', name: 'Bengali', native_name: 'বাংলা', voice_available: true },
  { code: 'ur', name: 'Urdu', native_name: 'اردو', voice_available: true },
  { code: 'pa', name: 'Punjabi', native_name: 'ਪੰਜਾਬੀ', voice_available: true },
  { code: 'or', name: 'Odia', native_name: 'ଓଡ଼ିଆ', voice_available: true },
];

type Translations = Record<string, Record<string, string>>;

const translations: Translations = {
  en: {
    appName: 'YatraSaathi',
    tagline: 'Voice-Enabled Bus Aggregator',
    searchBuses: 'Search Buses',
    popularRoutes: 'Popular Routes',
    home: 'Home',
    login: 'Login',
    signup: 'Sign Up',
    admin: 'Admin',
    selectLanguage: 'Language',
    
    heroBadge: 'Compare 6 OTAs in one search',
    heroTitle1: 'Find the cheapest bus ticket,',
    heroTitle2: 'every single time.',
    heroSubtitle: 'Compare fares across redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip, and Paytm Bus. One search, all options, best price guaranteed.',
    noHiddenCharges: 'No hidden charges',
    instantResults: 'Instant results',
    bestPrice: 'Best price from 6 OTAs',
    
    fromLabel: 'From / Departure City',
    toLabel: 'To / Destination City',
    dateLabel: 'Travel Date',
    selectOrigin: 'Select origin city',
    selectDestination: 'Select destination city',
    searchBtn: 'Search Buses',
    swapBtn: 'Swap cities',
    
    popRoutesTitle: 'Popular Bus Routes',
    popRoutesSub: 'Most searched bus routes across top Indian cities',
    viewAll: 'View all',
    from: 'From',
    to: 'to',
    startingFrom: 'From ₹',
    
    voiceTitle: 'Voice Bus Search',
    voiceHint: 'Tap the mic & speak your route in your preferred language (e.g., "buses from Hyderabad to Vijayawada tomorrow")',
    recording: 'Listening... Speak your journey details',
    processing: 'Processing your voice request...',
    stopRecording: 'Tap to Stop',
    speakNow: 'Tap to Speak',
    voiceLanguageLabel: 'Voice Language',

    resultsTitle: 'Bus Search Results',
    busesFound: 'buses found',
    sortBy: 'Sort by',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    ratingHighLow: 'Rating: High to Low',
    departureTime: 'Departure Time',
    duration: 'Duration',
    filterTitle: 'Filter Buses',
    busType: 'Bus Type',
    acStatus: 'AC Type',
    busModel: 'Bus Model',
    maxPriceLabel: 'Max Price',
    minRatingLabel: 'Min Rating',
    allTypes: 'All Types',
    sleeper: 'Sleeper',
    semiSleeper: 'Semi-Sleeper',
    seater: 'Seater',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'Booking Platforms',
    resetFilters: 'Reset Filters',
    noBuses: 'No bus listings found for this route.',
    tryDifferentDate: 'Try changing dates or selecting another city pair.',

    seatsLeft: 'seats left',
    compareFares: 'Compare Fares Across 6 OTAs',
    cheapestDeal: 'Cheapest Deal',
    bookOn: 'Book on',
    bookTicket: 'Book Ticket & Select Seat',
    durationMins: 'hrs',

    selectSeatTitle: 'Select Seats & Passenger Details',
    lowerBerth: 'Lower Deck',
    upperBerth: 'Upper Deck',
    selectedSeats: 'Selected Seats',
    passengerName: 'Full Name',
    passengerAge: 'Age',
    passengerGender: 'Gender',
    mobileNumber: 'Mobile Number',
    emailAddress: 'Email Address',
    paymentMethod: 'Select Payment Method',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'Credit / Debit Card',
    netBanking: 'Net Banking',
    baseFare: 'Base Fare',
    gstTaxes: 'Taxes & Service Fee',
    totalPayable: 'Total Amount Payable',
    confirmPay: 'Pay & Confirm Ticket',
    ticketConfirmed: 'Booking Confirmed!',
    pnrNumber: 'PNR Number',
    downloadTicket: 'Download Ticket',

    footerRights: 'All rights reserved. India’s multi-lingual smart bus tickets aggregator.',
  },

  te: {
    appName: 'యాత్రా సాథి',
    tagline: 'వాయిస్ సపోర్ట్‌తో బస్సు టికెట్లు',
    searchBuses: 'బస్సులను వెతకండి',
    popularRoutes: 'పాపులర్ మార్గాలు',
    home: 'హోమ్',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    admin: 'అడ్మిన్',
    selectLanguage: 'భాష',
    
    heroBadge: 'ఒకే శోధనలో 6 యాప్‌ల ధరల పోలిక',
    heroTitle1: 'అతి తక్కువ ధరకే బస్సు టికెట్,',
    heroTitle2: 'ప్రతిసారీ పొందండి.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip మరియు Paytm Bus ల ధరలను పోల్చండి.',
    noHiddenCharges: 'హిడెన్ ఛార్జీలు లేవు',
    instantResults: 'వెంటనే ఫలితాలు',
    bestPrice: '6 యాప్‌ల నుండి ఉత్తమ ధర',
    
    fromLabel: 'బయలుదేరే నగరం (From)',
    toLabel: 'చేరుకునే నగరం (To)',
    dateLabel: 'ప్రయాణ తేదీ',
    selectOrigin: 'బయలుదేరే నగరాన్ని ఎంచుకోండి',
    selectDestination: 'చేరుకునే నగరాన్ని ఎంచుకోండి',
    searchBtn: 'బస్సులను వెతకండి',
    swapBtn: 'నగరాలను మార్చండి',
    
    popRoutesTitle: 'పాపులర్ బస్సు రూట్లు',
    popRoutesSub: 'అత్యధికంగా శోధించిన బస్సు మార్గాలు',
    viewAll: 'అన్నీ చూడండి',
    from: 'నుండి',
    to: 'కి',
    startingFrom: 'ప్రారంభ ధర ₹',
    
    voiceTitle: 'వాయిస్ బస్సు సెర్చ్',
    voiceHint: 'మైక్ నొక్కి మీరు వెళ్లాల్సిన ఊరు గురించి మాట్లాడండి (ఉదా: "రేపు వైజాగ్ నుండి హైదరాబాద్ బస్సులు")',
    recording: 'వింటున్నాము... మీ ప్రయాణ వివరాలు చెప్పండి',
    processing: 'మీ వాయిస్ ప్రాసెస్ అవుతోంది...',
    stopRecording: 'ఆపడానికి నొక్కండి',
    speakNow: 'మాట్లాడటానికి మైక్ నొక్కండి',
    voiceLanguageLabel: 'వాయిస్ భాష',

    resultsTitle: 'బస్సు శోధన ఫలితాలు',
    busesFound: 'బస్సులు అందుబాటులో ఉన్నాయి',
    sortBy: 'వరుస క్రమం',
    priceLowHigh: 'ధర: తక్కువ నుండి ఎక్కువ',
    priceHighLow: 'ధర: ఎక్కువ నుండి తక్కువ',
    ratingHighLow: 'రేటింగ్: ఎక్కువ నుండి తక్కువ',
    departureTime: 'బయలుదేరే సమయం',
    duration: 'ప్రయాణ సమయం',
    filterTitle: 'ఫిల్టర్లు',
    busType: 'బస్సు రకం',
    acStatus: 'AC రకం',
    busModel: 'బస్సు మోడల్',
    maxPriceLabel: 'గరిష్ట ధర',
    minRatingLabel: 'కనిష్ట రేటింగ్',
    allTypes: 'అన్ని రకాలు',
    sleeper: 'స్లీపర్',
    semiSleeper: 'సెమీ-స్లీపర్',
    seater: 'సీటర్',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'బుకింగ్ యాప్‌లు',
    resetFilters: 'ఫిల్టర్లు రీసెట్ చేయండి',
    noBuses: 'ఈ రూట్‌లో బస్సులు కనిపించలేదు.',
    tryDifferentDate: 'వేరే తేదీ లేదా నగరాన్ని ఎంచుకోండి.',

    seatsLeft: 'సీట్లు ఉన్నాయి',
    compareFares: '6 యాప్‌లలో ధరలు చూడండి',
    cheapestDeal: 'అత్యంత తక్కువ ధర',
    bookOn: 'పై బుక్ చేయండి',
    bookTicket: 'సీటు ఎంచుకుని బుక్ చేయండి',
    durationMins: 'గంటలు',

    selectSeatTitle: 'సీట్లు మరియు ప్రయాణీకుల వివరాలు',
    lowerBerth: 'కింది డెక్',
    upperBerth: 'పై డెక్',
    selectedSeats: 'ఎంచుకున్న సీట్లు',
    passengerName: 'పూర్తి పేరు',
    passengerAge: 'వయస్సు',
    passengerGender: 'లింగం',
    mobileNumber: 'ఫోన్ నంబర్',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    paymentMethod: 'చెల్లింపు విధానం ఎంచుకోండి',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'క్రెడిట్ / డెబిట్ కార్డ్',
    netBanking: 'నెట్ బ్యాంకింగ్',
    baseFare: 'మూల ధర',
    gstTaxes: 'పన్నులు & సేవా రుసుము',
    totalPayable: 'మొత్తం చెల్లించాల్సిన మొత్తం',
    confirmPay: 'చెల్లించి టికెట్ ఖరారు చేయండి',
    ticketConfirmed: 'బుకింగ్ విజయవంతమైంది!',
    pnrNumber: 'PNR నంబర్',
    downloadTicket: 'టికెట్ డౌన్‌లోడ్ చేయండి',

    footerRights: 'అన్ని హక్కులు ప్రత్యేకించబడ్డాయి. భారతదేశపు మల్టీలింగువల్ బస్సు టికెట్ యాప్.',
  },

  hi: {
    appName: 'यात्रा साथी',
    tagline: 'वॉयस-सक्षम बस टिकट खोजें',
    searchBuses: 'बसें खोजें',
    popularRoutes: 'लोकप्रिय मार्ग',
    home: 'होम',
    login: 'लॉग इन',
    signup: 'साइन अप',
    admin: 'एडमिन',
    selectLanguage: 'भाषा',
    
    heroBadge: 'एक ही खोज में 6 ऐप्स के किराए की तुलना करें',
    heroTitle1: 'पाएं सबसे सस्ती बस टिकट,',
    heroTitle2: 'हर एक बार।',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip और Paytm Bus के किरायों की तुलना करें।',
    noHiddenCharges: 'कोई छिपा हुआ शुल्क नहीं',
    instantResults: 'तुरंत परिणाम',
    bestPrice: '6 ऐप्स से सबसे कम कीमत',
    
    fromLabel: 'प्रस्थान शहर (From)',
    toLabel: 'गंतव्य शहर (To)',
    dateLabel: 'यात्रा तिथि',
    selectOrigin: 'प्रस्थान शहर चुनें',
    selectDestination: 'गंतव्य शहर चुनें',
    searchBtn: 'बसें खोजें',
    swapBtn: 'शहर बदलें',
    
    popRoutesTitle: 'लोकप्रिय बस मार्ग',
    popRoutesSub: 'प्रमुख भारतीय शहरों के बीच सबसे अधिक खोजे गए मार्ग',
    viewAll: 'सभी देखें',
    from: 'से',
    to: 'तक',
    startingFrom: 'शुरुआती किराया ₹',
    
    voiceTitle: 'वॉयस बस खोज',
    voiceHint: 'माइक दबाएं और अपनी यात्रा बोलें (जैसे: "कल दिल्ली से जयपुर की बसें")',
    recording: 'सुन रहे हैं... अपनी यात्रा का विवरण बोलें',
    processing: 'आपकी आवाज को संसाधित किया जा रहा है...',
    stopRecording: 'रोकने के लिए दबाएं',
    speakNow: 'बोलने के लिए माइक दबाएं',
    voiceLanguageLabel: 'वॉयस भाषा',

    resultsTitle: 'बस खोज परिणाम',
    busesFound: 'बसें उपलब्ध हैं',
    sortBy: 'क्रमबद्ध करें',
    priceLowHigh: 'किराया: कम से अधिक',
    priceHighLow: 'किराया: अधिक से कम',
    ratingHighLow: 'रेटिंग: अधिक से कम',
    departureTime: 'प्रस्थान समय',
    duration: 'समय',
    filterTitle: 'फिल्टर',
    busType: 'बस का प्रकार',
    acStatus: 'एसी प्रकार',
    busModel: 'बस मॉडल',
    maxPriceLabel: 'अधिकतम किराया',
    minRatingLabel: 'न्यूनतम रेटिंग',
    allTypes: 'सभी प्रकार',
    sleeper: 'स्लीपर',
    semiSleeper: 'सेमी-स्लीपर',
    seater: 'सीटर',
    ac: 'AC',
    nonAc: 'नॉन-AC',
    otaFilter: 'बुकिंग प्लेटफॉर्म',
    resetFilters: 'फ़िल्टर रीसेट करें',
    noBuses: 'इस मार्ग के लिए कोई बस नहीं मिली।',
    tryDifferentDate: 'कृपया दूसरी तिथि या शहर चुनें।',

    seatsLeft: 'सीटें बची हैं',
    compareFares: '6 ऐप्स के किरायों की तुलना करें',
    cheapestDeal: 'सबसे सस्ता विकल्प',
    bookOn: 'पर बुक करें',
    bookTicket: 'सीट चुनें और बुक करें',
    durationMins: 'घंटे',

    selectSeatTitle: 'सीट और यात्री विवरण चुनें',
    lowerBerth: 'निचला डेक',
    upperBerth: 'ऊपरी डेक',
    selectedSeats: 'चुनी गई सीटें',
    passengerName: 'पूरा नाम',
    passengerAge: 'आयु',
    passengerGender: 'लिंग',
    mobileNumber: 'मोबाइल नंबर',
    emailAddress: 'ईमेल पता',
    paymentMethod: 'भुगतान विधि चुनें',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'क्रेडिट / डेबिट कार्ड',
    netBanking: 'नेट बैंकिंग',
    baseFare: 'मूल किराया',
    gstTaxes: 'कर और सेवा शुल्क',
    totalPayable: 'कुल देय राशि',
    confirmPay: 'भुगतान करें और टिकट कन्फर्म करें',
    ticketConfirmed: 'बुकिंग सफल रही!',
    pnrNumber: 'पीएनआर नंबर',
    downloadTicket: 'टिकट डाउनलोड करें',

    footerRights: 'सर्वाधिकार सुरक्षित। भारत का बहुभाषी स्मार्ट बस टिकट एग्रीगेटर।',
  },

  ta: {
    appName: 'யாத்ரா சாதி',
    tagline: 'குரல் வழி பேருந்து தேடல்',
    searchBuses: 'பேருந்துகளைத் தேடுங்கள்',
    popularRoutes: 'பிரபலமான பாதைகள்',
    home: 'முகப்பு',
    login: 'லாகின்',
    signup: 'சைன் அப்',
    admin: 'அட்மின்',
    selectLanguage: 'மொழி',
    
    heroBadge: '6 செயலிகளின் கட்டணங்களை ஒப்பிடுங்கள்',
    heroTitle1: 'மிகக் குறைந்த விலையில் பேருந்து டிக்கெட்,',
    heroTitle2: 'ஒவ்வொரு முறையும்.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip மற்றும் Paytm Bus கட்டணங்களை ஒப்பிடுங்கள்.',
    noHiddenCharges: 'மறைமுகக் கட்டணங்கள் இல்லை',
    instantResults: 'உடனடி முடிவுகள்',
    bestPrice: '6 செயலிகளில் சிறந்த விலை',
    
    fromLabel: 'புறப்படும் நகரம் (From)',
    toLabel: 'சென்றடையும் நகரம் (To)',
    dateLabel: 'பயண தேதி',
    selectOrigin: 'புறப்படும் நகரத்தை தேர்ந்தெடுக்கவும்',
    selectDestination: 'சென்றடையும் நகரத்தை தேர்ந்தெடுக்கவும்',
    searchBtn: 'பேருந்துகளைத் தேடுங்கள்',
    swapBtn: 'நகரங்களை மாற்றுக',
    
    popRoutesTitle: 'பிரபலமான பேருந்து பாதைகள்',
    popRoutesSub: 'அதிகம் தேடப்பட்ட பேருந்து பாதைகள்',
    viewAll: 'அனைத்தையும் காண்க',
    from: 'இருந்து',
    to: 'வரை',
    startingFrom: 'ஆரம்ப விலை ₹',
    
    voiceTitle: 'குரல் வழி பேருந்து தேடல்',
    voiceHint: 'மைக்கை அழுத்தி உங்கள் பயண விவரங்களை பேசுங்கள்',
    recording: 'கேட்கிறது... பேசுங்கள்',
    processing: 'செயலாக்கப்படுகிறது...',
    stopRecording: 'நிறுத்த அழுத்தவும்',
    speakNow: 'பேச மைக்கை அழுத்தவும்',
    voiceLanguageLabel: 'குரல் மொழி',

    resultsTitle: 'பேருந்து தேடல் முடிவுகள்',
    busesFound: 'பேருந்துகள் உள்ளன',
    sortBy: 'வரிசைப்படுத்து',
    priceLowHigh: 'விலை: குறைந்ததிலிருந்து அதிகம்',
    priceHighLow: 'விலை: அதிகத்திலிருந்து குறைவு',
    ratingHighLow: 'ரேட்டிங்: அதிகத்திலிருந்து குறைவு',
    departureTime: 'புறப்படும் நேரம்',
    duration: 'பயண நேரம்',
    filterTitle: 'வடிகட்டிகள்',
    busType: 'பேருந்து வகை',
    acStatus: 'ஏசி வகை',
    busModel: 'பேருந்து மாடல்',
    maxPriceLabel: 'அதிகபட்ச விலை',
    minRatingLabel: 'குறைந்தபட்ச ரேட்டிங்',
    allTypes: 'அனைத்து வகைகள்',
    sleeper: 'ஸ்லீப்பர்',
    semiSleeper: 'செமி-ஸ்லீப்பர்',
    seater: 'சீட்டர்',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'புக்கிங் செயலிகள்',
    resetFilters: 'மீட்டமைக்க',
    noBuses: 'இந்த பாதையில் பேருந்துகள் இல்லை.',
    tryDifferentDate: 'வேறு தேதியை தேர்ந்தெடுக்கவும்.',

    seatsLeft: 'இருக்கைகள் உள்ளன',
    compareFares: '6 செயலிகளின் கட்டணங்களை ஒப்பிடுக',
    cheapestDeal: 'மிகக் குறைந்த விலை',
    bookOn: 'இல் முன்பதிவு செய்க',
    bookTicket: 'இருக்கை தேர்வு செய்து முன்பதிவு செய்க',
    durationMins: 'மணிநேரம்',

    selectSeatTitle: 'இருக்கை மற்றும் பயணி விவரங்கள்',
    lowerBerth: 'கீழ் தளம்',
    upperBerth: 'மேல் தளம்',
    selectedSeats: 'தேர்ந்தெடுக்கப்பட்ட இருக்கைகள்',
    passengerName: 'முழு பெயர்',
    passengerAge: 'வயது',
    passengerGender: 'பாலினம்',
    mobileNumber: 'மொபைல் எண்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    paymentMethod: 'பணம் செலுத்தும் முறை',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'கிரெடிட் / டெபிட் கார்டு',
    netBanking: 'நெட் பேங்கிங்',
    baseFare: 'அடிப்படை கட்டணம்',
    gstTaxes: 'வரிகள் & સેવાக் கட்டணம்',
    totalPayable: 'மொத்தம் செலுத்த வேண்டியது',
    confirmPay: 'பணம் செலுத்தி உறுதி செய்க',
    ticketConfirmed: 'முன்பதிவு உறுதி செய்யப்பட்டது!',
    pnrNumber: 'PNR எண்',
    downloadTicket: 'டிக்கெட் பதிவிறக்கவும்',

    footerRights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
  },

  kn: {
    appName: 'ಯಾತ್ರಾ ಸಾಥಿ',
    tagline: 'ವಾಯ್ಸ್ ಮೂಲಕ ಬಸ್ ಟಿಕೆಟ್ ಹುಡುಕಾಟ',
    searchBuses: 'ಬಸ್‌ಗಳನ್ನು ಹುಡುಕಿ',
    popularRoutes: 'ಜನಪ್ರಿಯ ಮಾರ್ಗಗಳು',
    home: 'ಹೋಮ್',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    admin: 'ಅಡ್ಮಿನ್',
    selectLanguage: 'ಭಾಷೆ',
    
    heroBadge: '6 ಆಪ್‌ಗಳಲ್ಲಿ ದರಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ',
    heroTitle1: 'ಅತಿ ಕಡಿಮೆ ದರದಲ್ಲಿ ಬಸ್ ಟಿಕೆಟ್,',
    heroTitle2: 'ಪ್ರತಿ ಬಾರಿಯೂ ಪಡೆಯಿರಿ.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip ಮತ್ತು Paytm Bus ದರಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ.',
    noHiddenCharges: 'ಯಾವುದೇ ಗುಪ್ತ ಶುಲ್ಕವಿಲ್ಲ',
    instantResults: 'ತಕ್ಷಣದ ಫಲಿತಾಂಶಗಳು',
    bestPrice: 'ಉತ್ತಮ ಬೆಲೆ ಖಾತರಿ',
    
    fromLabel: 'ಹೊರಡುವ ನಗರ (From)',
    toLabel: 'ತಲುಪುವ ನಗರ (To)',
    dateLabel: 'ಪ್ರಯಾಣದ ದಿನಾಂಕ',
    selectOrigin: 'ಹೊರಡುವ ನಗರ ಆಯ್ಕೆಮಾಡಿ',
    selectDestination: 'ತಲುಪುವ ನಗರ ಆಯ್ಕೆಮಾಡಿ',
    searchBtn: 'ಬಸ್‌ಗಳನ್ನು ಹುಡುಕಿ',
    swapBtn: 'ನಗರಗಳನ್ನು ಬದಲಾಯಿಸಿ',
    
    popRoutesTitle: 'ಜನಪ್ರಿಯ ಬಸ್ ಮಾರ್ಗಗಳು',
    popRoutesSub: 'ಹೆಚ್ಚು ಹುಡುಕಲ್ಪಟ್ಟ ಬಸ್ ಮಾರ್ಗಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    from: 'ಇಂದ',
    to: 'ಗೆ',
    startingFrom: 'ಆರಂಭಿಕ ದರ ₹',
    
    voiceTitle: 'ವಾಯ್ಸ್ ಬಸ್ ಶೋಧನೆ',
    voiceHint: 'ಮೈಕ್ ಒತ್ತಿ ನಿಮ್ಮ ಪ್ರಯಾಣದ ವಿವರಗಳನ್ನು ಮಾತನಾಡಿ',
    recording: 'ಆಲಿಸಲಾಗುತ್ತಿದೆ... ಮಾತನಾಡಿ',
    processing: 'ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ...',
    stopRecording: 'ನಿಲ್ಲಿಸಲು ಒತ್ತಿ',
    speakNow: 'ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿ',
    voiceLanguageLabel: 'ವಾಯ್ಸ್ ಭಾಷೆ',

    resultsTitle: 'ಬಸ್ ಹುಡುಕಾಟದ ಫಲಿತಾಂಶಗಳು',
    busesFound: 'ಬಸ್‌ಗಳು ಲಭ್ಯವಿವೆ',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    priceLowHigh: 'ದರ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚು',
    priceHighLow: 'ದರ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆ',
    ratingHighLow: 'ರೇಟಿಂಗ್: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆ',
    departureTime: 'ಹೊರಡುವ ಸಮಯ',
    duration: 'ಪ್ರಯಾಣ ಸಮಯ',
    filterTitle: 'ಫಿಲ್ಟರ್‌ಗಳು',
    busType: 'ಬಸ್ ಮಾದರಿ',
    acStatus: 'AC ಮಾದರಿ',
    busModel: 'ಬಸ್ ಮಾಡೆಲ್',
    maxPriceLabel: 'ಗರಿಷ್ಠ ದರ',
    minRatingLabel: 'ಕನಿಷ್ಠ ರೇಟಿಂಗ್',
    allTypes: 'ಎಲ್ಲಾ ಮಾದರಿಗಳು',
    sleeper: 'ಸ್ಲೀಪರ್',
    semiSleeper: 'ಸೆಮಿ-ಸ್ಲೀಪರ್',
    seater: 'ಸೀಟರ್',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'ಬುಕಿಂಗ್ ಆಪ್‌ಗಳು',
    resetFilters: 'ಮರುಹೊಂದಿಸಿ',
    noBuses: 'ಈ ಮಾರ್ಗದಲ್ಲಿ ಬಸ್‌ಗಳು ಸಿಗಲಿಲ್ಲ.',
    tryDifferentDate: 'ಮತ್ತೊಂದು ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ.',

    seatsLeft: 'ಸೀಟುಗಳು ಲಭ್ಯವಿವೆ',
    compareFares: '6 ಆಪ್‌ಗಳ ದರಗಳನ್ನು ಹೋಲಿಸಿ',
    cheapestDeal: 'ಅತಿ ಅಗ್ಗದ ದರ',
    bookOn: 'ನಲ್ಲಿ ಬುಕ್ ಮಾಡಿ',
    bookTicket: 'ಸೀಟು ಆಯ್ಕೆಮಾಡಿ ಬುಕ್ ಮಾಡಿ',
    durationMins: 'ಗಂಟೆಗಳು',

    selectSeatTitle: 'ಸೀಟು ಮತ್ತು ಪ್ರಯಾಣಿಕರ ವಿವರಗಳು',
    lowerBerth: 'ಕೆಳಗಿನ ಡೆಕ್',
    upperBerth: 'ಮೇಲಿನ ಡೆಕ್',
    selectedSeats: 'ಆಯ್ಕೆಮಾಡಿದ ಸೀಟುಗಳು',
    passengerName: 'ಪೂರ್ಣ ಹೆಸರು',
    passengerAge: 'ವಯಸ್ಸು',
    passengerGender: 'ಲಿಂಗ',
    mobileNumber: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    paymentMethod: 'ಪಾವತಿ ವಿಧಾನ ಆಯ್ಕೆಮಾಡಿ',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'ಕ್ರೆಡಿಟ್ / ಡೆಬಿಟ್ ಕಾರ್ಡ್',
    netBanking: 'ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್',
    baseFare: 'ಮೂಲ ದರ',
    gstTaxes: 'ತೆರಿಗೆಗಳು ಮತ್ತು ಸೇವಾ ಶುಲ್ಕ',
    totalPayable: 'ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ',
    confirmPay: 'ಪಾವತಿಸಿ ಟಿಕೆಟ್ ಖಚಿತಪಡಿಸಿ',
    ticketConfirmed: 'ಬುಕಿಂಗ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
    pnrNumber: 'PNR ಸಂಖ್ಯೆ',
    downloadTicket: 'ಟಿಕೆಟ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',

    footerRights: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
  },

  ml: {
    appName: 'യാത്രാ സാഥി',
    tagline: 'വോയ്സ് ബസ് ടിക്കറ്റ് സെർച്ച്',
    searchBuses: 'ബസുകൾ തിരയുക',
    popularRoutes: 'ജനപ്രിയ റൂട്ടുകൾ',
    home: 'ഹോം',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    admin: 'അഡ്മിൻ',
    selectLanguage: 'ഭാഷ',
    
    heroBadge: '6 ആപ്പുകളിലെ നിരക്കുകൾ താരതമ്യം ചെയ്യുക',
    heroTitle1: 'ഏറ്റവും കുറഞ്ഞ നിരക്കിൽ ബസ് ടിക്കറ്റ്,',
    heroTitle2: 'എല്ലാ തവണയും.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip, Paytm Bus നിരക്കുകൾ ഒരിടത്ത്.',
    noHiddenCharges: 'ഹിഡൻ ചാർജുകൾ ഇല്ല',
    instantResults: 'ഉടൻ ഫലങ്ങൾ',
    bestPrice: 'ഏറ്റവും മികച്ച നിരക്ക്',
    
    fromLabel: 'പുറപ്പെടുന്ന നഗരം (From)',
    toLabel: 'എത്തിച്ചേരേണ്ട നഗരം (To)',
    dateLabel: 'യാത്രാ തീയതി',
    selectOrigin: 'പുറപ്പെടുന്ന നഗരം തിരഞ്ഞെടുക്കുക',
    selectDestination: 'എത്തിച്ചേരേണ്ട നഗരം തിരഞ്ഞെടുക്കുക',
    searchBtn: 'ബസുകൾ തിരയുക',
    swapBtn: 'മാറ്റുക',
    
    popRoutesTitle: 'ജനപ്രിയ ബസ് റൂട്ടുകൾ',
    popRoutesSub: 'കൂടുതലായി തിരഞ്ഞ റൂട്ടുകൾ',
    viewAll: 'എല്ലാം കാണുക',
    from: 'നിന്ന്',
    to: 'ലേക്ക്',
    startingFrom: 'ആരംഭ നിരക്ക് ₹',
    
    voiceTitle: 'വോയ്സ് ബസ് സെർച്ച്',
    voiceHint: 'മൈക്കിൽ തൊട്ട് നിങ്ങളുടെ യാത്രയെക്കുറിച്ച് സംസാരിക്കുക',
    recording: 'ശ്രദ്ധിക്കുന്നു... സംസാരിക്കുക',
    processing: 'പ്രോസസ്സ് ചെയ്യുന്നു...',
    stopRecording: 'നിർത്താൻ അമർത്തുക',
    speakNow: 'സംസാരിക്കാൻ അമർത്തുക',
    voiceLanguageLabel: 'വോയ്സ് ഭാഷ',

    resultsTitle: 'ബസ് ഫലങ്ങൾ',
    busesFound: 'ബസുകൾ ലഭ്യമാണ്',
    sortBy: 'ക്രമീകരിക്കുക',
    priceLowHigh: 'നിരക്ക്: കുറഞ്ഞതിൽ നിന്ന് കൂടിയതിലേക്ക്',
    priceHighLow: 'നിരക്ക്: ഉയർന്നതിൽ നിന്ന് താഴ്ന്നതിലേക്ക്',
    ratingHighLow: 'റേറ്റിംഗ്: ഉയർന്നതിൽ നിന്ന് താഴ്ന്നതിലേക്ക്',
    departureTime: 'പുറപ്പെടുന്ന സമയം',
    duration: 'യാത്രാ സമയം',
    filterTitle: 'ഫിൽട്ടറുകൾ',
    busType: 'ബസ് ടൈപ്പ്',
    acStatus: 'AC ടൈപ്പ്',
    busModel: 'ബസ് മോഡൽ',
    maxPriceLabel: 'പരമാവധി നിരക്ക്',
    minRatingLabel: 'കുറഞ്ഞ റേറ്റിംഗ്',
    allTypes: 'എല്ലാ തരം',
    sleeper: 'സ്ലീപ്പർ',
    semiSleeper: 'സെമി സ്ലീപ്പർ',
    seater: 'സീറ്റർ',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'ബുക്കിംഗ് ആപ്പുകൾ',
    resetFilters: 'റീസെറ്റ്',
    noBuses: 'ഈ റൂട്ടിൽ ബസുകൾ കണ്ടെത്തിയില്ല.',
    tryDifferentDate: 'മറ്റൊരു തീയതി തിരഞ്ഞെടുക്കുക.',

    seatsLeft: 'സീറ്റുകൾ ബാക്കിയുണ്ട്',
    compareFares: '6 ആപ്പുകളുടെ നിരക്ക് കാണുക',
    cheapestDeal: 'ഏറ്റവും കുറഞ്ഞ നിരക്ക്',
    bookOn: 'ൽ ബുക്ക് ചെയ്യുക',
    bookTicket: 'സീറ്റ് തിരഞ്ഞെടുത്ത് ബുക്ക് ചെയ്യുക',
    durationMins: 'മണിക്കൂർ',

    selectSeatTitle: 'സീറ്റും യാത്രക്കാരുടെ വിവരങ്ങളും',
    lowerBerth: 'താഴത്തെ ഡെക്ക്',
    upperBerth: 'മുകളിലത്തെ ഡെക്ക്',
    selectedSeats: 'തിരഞ്ഞെടുത്ത സീറ്റുകൾ',
    passengerName: 'പൂർണ്ണമായ പേര്',
    passengerAge: 'പ്രായം',
    passengerGender: 'ലിംഗം',
    mobileNumber: 'മൊബൈൽ നമ്പർ',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    paymentMethod: 'പേയ്മെന്റ് രീതി തിരഞ്ഞെടുക്കുക',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'ക്രെഡിറ്റ് / ഡെബിറ്റ് കാർഡ്',
    netBanking: 'നെറ്റ് ബാങ്കിംഗ്',
    baseFare: 'അടിസ്ഥാന നിരക്ക്',
    gstTaxes: 'നികുതികളും സേവന ഫീസും',
    totalPayable: 'ആകെ നൽകേണ്ട തുക',
    confirmPay: 'പണം നൽകി ടിക്കറ്റ് ഉറപ്പാക്കുക',
    ticketConfirmed: 'ബുക്കിംഗ് വിജയകരമായി!',
    pnrNumber: 'PNR നമ്പർ',
    downloadTicket: 'ടിക്കറ്റ് ഡൗൺലോഡ് ചെയ്യുക',

    footerRights: 'എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം.',
  },

  mr: {
    appName: 'यात्रा साथी',
    tagline: 'व्हॉइस बस तिकीट शोध',
    searchBuses: 'बस शोधा',
    popularRoutes: 'लोकप्रिय मार्ग',
    home: 'होम',
    login: 'लॉगिन',
    signup: 'साइन अप',
    admin: 'ॲडमिन',
    selectLanguage: 'भाषा',
    
    heroBadge: 'एकाच शोधात ६ ॲप्सच्या तिकिटांची तुलना करा',
    heroTitle1: 'मिळावा सर्वात स्वस्त बस तिकीट,',
    heroTitle2: 'प्रत्येक वेळी.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip आणि Paytm Bus च्या दरांची तुलना करा.',
    noHiddenCharges: 'कोणतेही लपवलेले शुल्क नाही',
    instantResults: 'झटपट निकाल',
    bestPrice: 'सर्वोत्तम दराची खात्री',
    
    fromLabel: 'निघण्याचे शहर (From)',
    toLabel: 'पोहोचण्याचे शहर (To)',
    dateLabel: 'प्रवासाची तारीख',
    selectOrigin: 'निघण्याचे शहर निवडा',
    selectDestination: 'पोहोचण्याचे शहर निवडा',
    searchBtn: 'बस शोधा',
    swapBtn: 'शहर बदला',
    
    popRoutesTitle: 'लोकप्रिय बस मार्ग',
    popRoutesSub: 'सर्वाधिक शोधले गेलेले मार्ग',
    viewAll: 'सर्व पाहा',
    from: 'पासून',
    to: 'पर्यंत',
    startingFrom: 'शुरुआतीचा दर ₹',
    
    voiceTitle: 'व्हॉइस बस शोध',
    voiceHint: 'माईक दाबा आणि तुमच्या प्रवासाबद्दल बोला',
    recording: 'एकत आहे... बोला',
    processing: 'प्रक्रिया सुरू आहे...',
    stopRecording: 'थांबवण्यासाठी दाबा',
    speakNow: 'बोलण्यासाठी दाबा',
    voiceLanguageLabel: 'व्हॉइस भाषा',

    resultsTitle: 'बस शोध निकाल',
    busesFound: 'बस उपलब्ध आहेत',
    sortBy: 'क्रमवारी',
    priceLowHigh: 'दर: कमी ते जास्त',
    priceHighLow: 'दर: जास्त ते कमी',
    ratingHighLow: 'रेटिंग: जास्त ते कमी',
    departureTime: 'निघण्याची वेळ',
    duration: 'वेळ',
    filterTitle: 'फिल्टर्स',
    busType: 'बसचा प्रकार',
    acStatus: 'AC प्रकार',
    busModel: 'बस मॉडेल',
    maxPriceLabel: 'जास्तीत जास्त दर',
    minRatingLabel: 'किमान रेटिंग',
    allTypes: 'सर्व प्रकार',
    sleeper: 'स्लीपर',
    semiSleeper: 'सेमी-स्लीपर',
    seater: 'सीटर',
    ac: 'AC',
    nonAc: 'नॉन-AC',
    otaFilter: 'बुकिंग ॲप्स',
    resetFilters: 'रिसेट करा',
    noBuses: 'या मार्गावर बस उपलब्ध नाहीत.',
    tryDifferentDate: 'कृपया दुसरी तारीख निवडा.',

    seatsLeft: 'सीट्स शिल्लक आहेत',
    compareFares: '६ ॲप्सच्या दरांची तुलना करा',
    cheapestDeal: 'सर्वात स्वस्त दर',
    bookOn: 'वर बुक करा',
    bookTicket: 'सीट निवडून बुक करा',
    durationMins: 'तास',

    selectSeatTitle: 'सीट आणि प्रवाशांचे तपशील',
    lowerBerth: 'खालचा मजला',
    upperBerth: 'वरचा मजला',
    selectedSeats: 'निवडलेल्या सीट्स',
    passengerName: 'पूर्ण नाव',
    passengerAge: 'वय',
    passengerGender: 'लिंग',
    mobileNumber: 'मोबाईल नंबर',
    emailAddress: 'ईमेल पत्ता',
    paymentMethod: 'पेमेंट पद्धत निवडा',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'क्रेडिट / डेबिट कार्ड',
    netBanking: 'नेट बँकिंग',
    baseFare: 'मूळ दर',
    gstTaxes: 'कर आणि सेवा शुल्क',
    totalPayable: 'एकूण देय रक्कम',
    confirmPay: 'पेमेंट करा आणि तिकीट निश्चित करा',
    ticketConfirmed: 'बुकिंग यशस्वी!',
    pnrNumber: 'PNR नंबर',
    downloadTicket: 'तिकीट डाउनलोड करा',

    footerRights: 'सर्व हक्क राखीव.',
  },

  gu: {
    appName: 'યાત્રા સાથી',
    tagline: 'વોઈસ બસ ટિકિટ સર્ચ',
    searchBuses: 'બસ શોધો',
    popularRoutes: 'લોકપ્રિય રૂટ',
    home: 'હોમ',
    login: 'લોગિન',
    signup: 'સાઇન અપ',
    admin: 'એડમિન',
    selectLanguage: 'ભાષા',
    
    heroBadge: '૬ એપ્સના ભાડાની સરખામણી કરો',
    heroTitle1: 'મેળવો સૌથી સસ્તી બસ ટિકિટ,',
    heroTitle2: 'દરેક વખતે.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip અને Paytm Bus ના ભાડાની સરખામણી કરો.',
    noHiddenCharges: 'કોઈ છુપો ચાર્જ નથી',
    instantResults: 'ત્વરિત પરિણામો',
    bestPrice: 'સૌથી ઓછી કિંમત',
    
    fromLabel: 'ઉપડવાનું શહેર (From)',
    toLabel: 'પહોંચવાનું શહેર (To)',
    dateLabel: 'મુસાફરીની તારીખ',
    selectOrigin: 'ઉપડવાનું શહેર પસંદ કરો',
    selectDestination: 'પહોંચવાનું શહેર પસંદ કરો',
    searchBtn: 'બસ શોધો',
    swapBtn: 'બદલો',
    
    popRoutesTitle: 'લોકપ્રિય બસ રૂટ',
    popRoutesSub: 'સૌથી વધુ શોધાયેલા રૂટ',
    viewAll: 'બધું જુઓ',
    from: 'થી',
    to: 'સુધી',
    startingFrom: 'શરૂઆતી ભાડું ₹',
    
    voiceTitle: 'વોઈસ બસ સર્ચ',
    voiceHint: 'માઈક દબાવો અને તમારી મુસાફરી વિશે બોલો',
    recording: 'સાંભળી રહ્યા છીએ... બોલો',
    processing: 'પ્રોસેસિંગ થઈ રહ્યું છે...',
    stopRecording: 'રોકવા માટે દબાવો',
    speakNow: 'બોલવા માટે દબાવો',
    voiceLanguageLabel: 'વોઈસ ભાષા',

    resultsTitle: 'બસ શોધો પરિણામ',
    busesFound: 'બસ ઉપલબ્ધ છે',
    sortBy: 'ક્રમબદ્ધ કરો',
    priceLowHigh: 'ભાડું: ઓછું થી વધુ',
    priceHighLow: 'ભાડું: વધુ થી ઓછું',
    ratingHighLow: 'રેટિંગ: વધુ થી ઓછું',
    departureTime: 'ઉપડવાનો સમય',
    duration: 'સમય',
    filterTitle: 'ફિલ્ટર્સ',
    busType: 'બસનો પ્રકાર',
    acStatus: 'AC પ્રકાર',
    busModel: 'બસ મોડેલ',
    maxPriceLabel: 'મહત્તમ ભાડું',
    minRatingLabel: 'ન્યૂનતમ રેટિંગ',
    allTypes: 'તમામ પ્રકાર',
    sleeper: 'સ્લીપર',
    semiSleeper: 'સેમી-સ્લીપર',
    seater: 'સીટર',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'બુકિંગ એપ્સ',
    resetFilters: 'રીસેટ કરો',
    noBuses: 'આ રૂટ માટે કોઈ બસ મળી નથી.',
    tryDifferentDate: 'બીજી તારીખ પસંદ કરો.',

    seatsLeft: 'સીટો ઉપલબ્ધ છે',
    compareFares: '૬ એપ્સના ભાડા જુઓ',
    cheapestDeal: 'સૌથી સસ્તું ભાડું',
    bookOn: 'પર બુક કરો',
    bookTicket: 'સીટ પસંદ કરી બુક કરો',
    durationMins: 'કલાક',

    selectSeatTitle: 'સીટ અને મુસાફરની વિગતો',
    lowerBerth: 'નીચલી ડેક',
    upperBerth: 'ઉપરની ડેક',
    selectedSeats: 'પસંદ કરેલી સીટો',
    passengerName: 'પૂરું નામ',
    passengerAge: 'ઉંમર',
    passengerGender: 'જિન્ડર',
    mobileNumber: 'મોબાઈલ નંબર',
    emailAddress: 'ઈમેઈલ સરનામું',
    paymentMethod: 'ચુકવણી પદ્ધતિ પસંદ કરો',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'ક્રેડિટ / ડેબિટ કાર્ડ',
    netBanking: 'નેટ બેંકિંગ',
    baseFare: 'મૂળ ભાડું',
    gstTaxes: 'ટેક્સ અને સેવા શુલ્ક',
    totalPayable: 'કુલ ચૂકવવાપાત્ર રકમ',
    confirmPay: 'ચુકવણી કરો અને ટિકિટ કન્ફર્મ કરો',
    ticketConfirmed: 'બુકિંગ સફળ રહ્યું!',
    pnrNumber: 'PNR નંબર',
    downloadTicket: 'ટિકિટ ડાઉનલોડ કરો',

    footerRights: 'તમામ હકો અનામત છે.',
  },

  bn: {
    appName: 'যাত্রা সাথী',
    tagline: 'ভয়েস বাস টিকিট অনুসন্ধান',
    searchBuses: 'বাস খুঁজুন',
    popularRoutes: 'জনপ্রিয় রুট',
    home: 'হোম',
    login: 'লগইন',
    signup: 'সাইন আপ',
    admin: 'অ্যাডমিন',
    selectLanguage: 'ভাষা',
    
    heroBadge: '৬টি অ্যাপের ভাড়ার তুলনা করুন',
    heroTitle1: 'সবচেয়ে কম দামে বাস টিকিট,',
    heroTitle2: 'প্রতিবার পান।',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip এবং Paytm Bus ভাড়ার তুলনা করুন।',
    noHiddenCharges: 'কোনো লুকানো চার্জ নেই',
    instantResults: 'তাত্ক্ষণিক ফলাফল',
    bestPrice: 'সেরা মূল্যের নিশ্চয়তা',
    
    fromLabel: 'যাত্রার শহর (From)',
    toLabel: 'গন্তব্য শহর (To)',
    dateLabel: 'ভ্রমণের তারিখ',
    selectOrigin: 'যাত্রার শহর নির্বাচন করুন',
    selectDestination: 'গন্তব্য শহর নির্বাচন করুন',
    searchBtn: 'বাস খুঁজুন',
    swapBtn: 'শহর পরিবর্তন করুন',
    
    popRoutesTitle: 'জনপ্রিয় বাস রুট',
    popRoutesSub: 'সর্বাধিক অনুসন্ধান করা বাস রুট',
    viewAll: 'সব দেখুন',
    from: 'থেকে',
    to: 'পর্যন্ত',
    startingFrom: 'শুরু মূল্য ₹',
    
    voiceTitle: 'ভয়েস বাস অনুসন্ধান',
    voiceHint: 'মাইক আলতো চাপুন এবং কথা বলুন',
    recording: 'শুনছি... বলুন',
    processing: 'প্রসেসিং হচ্ছে...',
    stopRecording: 'থামাতে চাপুন',
    speakNow: 'বলতে চাপুন',
    voiceLanguageLabel: 'ভয়েস ভাষা',

    resultsTitle: 'বাস অনুসন্ধানের ফলাফল',
    busesFound: 'টি বাস পাওয়া গেছে',
    sortBy: 'সাজান',
    priceLowHigh: 'ভাড়া: কম থেকে বেশি',
    priceHighLow: 'ভাড়া: বেশি থেকে কম',
    ratingHighLow: 'রেটিং: বেশি থেকে কম',
    departureTime: 'ছাড়ার সময়',
    duration: 'সময়কাল',
    filterTitle: 'ফিল্টার',
    busType: 'বাসের ধরন',
    acStatus: 'এসি ধরন',
    busModel: 'বাসের মডেল',
    maxPriceLabel: 'সর্বোচ্চ ভাড়া',
    minRatingLabel: 'সর্বনিম্ন রেটিং',
    allTypes: 'সব ধরন',
    sleeper: 'স্লিপার',
    semiSleeper: 'সেমি-স্লিপার',
    seater: 'সিটার',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'বুকিং অ্যাপস',
    resetFilters: 'রিসেট করুন',
    noBuses: 'এই রুটে কোনো বাস পাওয়া যায়নি।',
    tryDifferentDate: 'অন্য তারিখ বেছে নিন।',

    seatsLeft: 'টি সিট বাকি আছে',
    compareFares: '৬টি অ্যাপের ভাড়া তুলনা করুন',
    cheapestDeal: 'সবচেয়ে সস্তা অফার',
    bookOn: 'এ বুক করুন',
    bookTicket: 'সিট বেছে বুক করুন',
    durationMins: 'ঘণ্টা',

    selectSeatTitle: 'সিট ও যাত্রীর বিবরণ',
    lowerBerth: 'নিচের ডেক',
    upperBerth: 'উপরের ডেক',
    selectedSeats: 'নির্বাচিত সিট',
    passengerName: 'সম্পূর্ণ নাম',
    passengerAge: 'বয়স',
    passengerGender: 'লিঙ্গ',
    mobileNumber: 'মোবাইল নম্বর',
    emailAddress: 'ইমেল ঠিকানা',
    paymentMethod: 'পেমেন্ট পদ্ধতি বেছে নিন',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'ক্রেডিট / ডেবিট কার্ড',
    netBanking: 'নেট ব্যাংকিং',
    baseFare: 'মূল ভাড়া',
    gstTaxes: 'ট্যাক্স ও সার্ভিস ফি',
    totalPayable: 'মোট প্রদেয় অর্থ',
    confirmPay: 'পেমেন্ট করে টিকিট নিশ্চিত করুন',
    ticketConfirmed: 'বুকিং সফল হয়েছে!',
    pnrNumber: 'PNR নম্বর',
    downloadTicket: 'টিকিট ডাউনলোড করুন',

    footerRights: 'সর্বস্বত্ব সংরক্ষিত।',
  },

  ur: {
    appName: 'یا تـرا ساتھی',
    tagline: 'وائس بس ٹکٹ تلاش کریں',
    searchBuses: 'بسیں تلاش کریں',
    popularRoutes: 'مقبول راستے',
    home: 'ہوم',
    login: 'لاگ ان',
    signup: 'سائن اپ',
    admin: 'ایڈمن',
    selectLanguage: 'زبان',
    
    heroBadge: '6 ایپس کے کرایوں کا موازنہ کریں',
    heroTitle1: 'سب سے سستا بس ٹکٹ حاصل کریں،',
    heroTitle2: 'ہر بار۔',
    heroSubtitle: 'redBus، MakeMyTrip، AbhiBus، TravelYaari اور Paytm Bus کے کرایوں کا موازنہ کریں۔',
    noHiddenCharges: 'کوئی پوشیدہ چارجز نہیں',
    instantResults: 'فوری نتائج',
    bestPrice: 'بہترین قیمت کی ضمانت',
    
    fromLabel: 'روانگی کا شہر (From)',
    toLabel: 'منزل کا شہر (To)',
    dateLabel: 'سفر کی تاریخ',
    selectOrigin: 'روانگی کا شہر منتخب کریں',
    selectDestination: 'منزل کا شہر منتخب کریں',
    searchBtn: 'بسیں تلاش کریں',
    swapBtn: 'تبدیل کریں',
    
    popRoutesTitle: 'مقبول بس راستے',
    popRoutesSub: 'سب سے زیادہ تلاش کیے گئے راستے',
    viewAll: 'سب دیکھیں',
    from: 'سے',
    to: 'تک',
    startingFrom: 'ابتدائی کرایہ ₹',
    
    voiceTitle: 'وائس بس سرچ',
    voiceHint: 'مائیک پر ٹیپ کریں اور اپنے سفر کا بولیں',
    recording: 'سن رہے ہیں... بولیں',
    processing: 'پروسیسنگ جاری ہے...',
    stopRecording: 'روکنے کے لیے ٹیپ کریں',
    speakNow: 'بولنے کے لیے ٹیپ کریں',
    voiceLanguageLabel: 'وائس زبان',

    resultsTitle: 'بس تلاش کے نتائج',
    busesFound: 'بسیں دستیاب ہیں',
    sortBy: 'ترتیب دیں',
    priceLowHigh: 'کرایہ: کم سے زیادہ',
    priceHighLow: 'کرایہ: زیادہ سے کم',
    ratingHighLow: 'ریٹنگ: زیادہ سے کم',
    departureTime: 'روانگی کا وقت',
    duration: 'وقت',
    filterTitle: 'فلٹرز',
    busType: 'بس کی قسم',
    acStatus: 'AC قسم',
    busModel: 'بس ماڈل',
    maxPriceLabel: 'زیادہ سے زیادہ کرایہ',
    minRatingLabel: 'کم از کم ریٹنگ',
    allTypes: 'تمام اقسام',
    sleeper: 'سلیپر',
    semiSleeper: 'سیمی سلیپر',
    seater: 'سیٹر',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'بکنگ ایپس',
    resetFilters: 'ری سیٹ کریں',
    noBuses: 'اس راستے کے لیے کوئی بس نہیں ملی۔',
    tryDifferentDate: 'دوسری تاریخ منتخب کریں۔',

    seatsLeft: 'سیٹیں باقی ہیں',
    compareFares: '6 ایپس کے کرایے دیکھیں',
    cheapestDeal: 'سب سے سستی ڈیل',
    bookOn: 'پر بک کریں',
    bookTicket: 'سیٹ منتخب کریں اور بک کریں',
    durationMins: 'گھنٹے',

    selectSeatTitle: 'سیٹ اور مسافر کی تفصیلات',
    lowerBerth: 'نچلا ڈیک',
    upperBerth: 'اوپری ڈیک',
    selectedSeats: 'منتخب کردہ سیٹیں',
    passengerName: 'پورا نام',
    passengerAge: 'عمر',
    passengerGender: 'جنس',
    mobileNumber: 'موبائل نمبر',
    emailAddress: 'ای میل پتہ',
    paymentMethod: 'ادائیگی کا طریقہ منتخب کریں',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'کریڈٹ / ڈیبٹ کارڈ',
    netBanking: 'نیٹ بینکنگ',
    baseFare: 'بنیادی کرایہ',
    gstTaxes: 'ٹیکس اور سروس فیس',
    totalPayable: 'کل قابل ادائیگی رقم',
    confirmPay: 'ادائیگی کریں اور ٹکٹ کنفرم کریں',
    ticketConfirmed: 'بکنگ کامیاب ہو گئی!',
    pnrNumber: 'PNR نمبر',
    downloadTicket: 'ٹکٹ ڈاؤن لوڈ کریں',

    footerRights: 'جملہ حقوق محفوظ ہیں۔',
  },

  pa: {
    appName: 'ਯਾਤਰਾ ਸਾਥੀ',
    tagline: 'ਵੌਇਸ ਬੱਸ ਟਿਕਟ ਖੋਜ',
    searchBuses: 'ਬੱਸਾਂ ਖੋਜੋ',
    popularRoutes: 'ਮਸ਼ਹੂਰ ਰੂਟ',
    home: 'ਹੋਮ',
    login: 'ਲੌਗਇਨ',
    signup: 'ਸਾਈਨ ਅੱਪ',
    admin: 'ਐਡਮਿਨ',
    selectLanguage: 'ਭਾਸ਼ਾ',
    
    heroBadge: '6 ਐਪਸ ਦੇ ਕਿਰਾਏ ਦੀ ਤੁਲਨਾ ਕਰੋ',
    heroTitle1: 'ਸਭ ਤੋਂ ਸਸਤੀ ਬੱਸ ਟਿਕਟ ਪ੍ਰਾਪਤ ਕਰੋ,',
    heroTitle2: 'ਹਰ ਵਾਰ।',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip ਅਤੇ Paytm Bus ਦੇ ਕਿਰਾਏ ਦੇਖੋ।',
    noHiddenCharges: 'ਕੋਈ ਲੁਕਵਾਂ ਖਰਚਾ ਨਹੀਂ',
    instantResults: 'ਤੁਰੰਤ ਨਤੀਜੇ',
    bestPrice: 'ਸਭ ਤੋਂ ਵਧੀਆ ਕੀਮਤ',
    
    fromLabel: 'ਚੱਲਣ ਦਾ ਸ਼ਹਿਰ (From)',
    toLabel: 'ਪਹੁੰਚਣ ਦਾ ਸ਼ਹਿਰ (To)',
    dateLabel: 'ਯਾਤਰਾ ਦੀ ਮਿਤੀ',
    selectOrigin: 'ਚੱਲਣ ਦਾ ਸ਼ਹਿਰ ਚੁਣੋ',
    selectDestination: 'ਪਹੁੰਚਣ ਦਾ ਸ਼ਹਿਰ ਚੁਣੋ',
    searchBtn: 'ਬੱਸਾਂ ਖੋਜੋ',
    swapBtn: 'ਬਦਲੋ',
    
    popRoutesTitle: 'ਮਸ਼ਹੂਰ ਬੱਸ ਰੂਟ',
    popRoutesSub: 'ਸਭ ਤੋਂ ਵੱਧ ਖੋਜੇ ਗਏ ਰੂਟ',
    viewAll: 'ਸਭ ਦੇਖੋ',
    from: 'ਤੋਂ',
    to: 'ਤੱਕ',
    startingFrom: 'ਸ਼ੁਰੂਆਤੀ ਕਿਰਾਇਆ ₹',
    
    voiceTitle: 'ਵੌਇਸ ਬੱਸ ਖੋਜ',
    voiceHint: 'ਮਾਈਕ ਦਬਾਓ ਅਤੇ ਬੋਲੋ',
    recording: 'ਸੁਣ ਰਹੇ ਹਾਂ... ਬੋਲੋ',
    processing: 'ਪ੍ਰੋਸੈਸਿੰਗ ਹੋ ਰਹੀ ਹੈ...',
    stopRecording: 'ਰੋਕਣ ਲਈ ਦਬਾਓ',
    speakNow: 'ਬੋਲਣ ਲਈ ਦਬਾਓ',
    voiceLanguageLabel: 'ਵੌਇਸ ਭਾਸ਼ਾ',

    resultsTitle: 'ਬੱਸ ਖੋਜ ਦੇ ਨਤੀਜੇ',
    busesFound: 'ਬੱਸਾਂ ਮਿਲੀਆਂ ਹਨ',
    sortBy: 'ਕ੍ਰਮਬੱਧ ਕਰੋ',
    priceLowHigh: 'ਕਿਰਾਇਆ: ਘੱਟ ਤੋਂ ਵੱਧ',
    priceHighLow: 'ਕਿਰਾਇਆ: ਵੱਧ ਤੋਂ ਘੱਟ',
    ratingHighLow: 'ਰੇਟਿੰਗ: ਵੱਧ ਤੋਂ ਘੱਟ',
    departureTime: 'ਚੱਲਣ ਦਾ ਸਮਾਂ',
    duration: 'ਸਮਾਂ',
    filterTitle: 'ਫਿਲਟਰ',
    busType: 'ਬੱਸ ਦੀ ਕਿਸਮ',
    acStatus: 'AC ਕਿਸਮ',
    busModel: 'ਬੱਸ ਮਾਡਲ',
    maxPriceLabel: 'ਵੱਧ ਤੋਂ ਵੱਧ ਕਿਰਾਇਆ',
    minRatingLabel: 'ਘੱਟੋ-ਘੱਟ ਰੇਟਿੰਗ',
    allTypes: 'ਸਾਰੀਆਂ ਕਿਸਮਾਂ',
    sleeper: 'ਸਲੀਪਰ',
    semiSleeper: 'ਸੈਮੀ-ਸਲੀਪਰ',
    seater: 'ਸੀਟਰ',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'ਬੁਕਿੰਗ ਐਪਸ',
    resetFilters: 'ਰੀਸੈਟ ਕਰੋ',
    noBuses: 'ਇਸ ਰੂਟ ਲਈ ਕੋਈ ਬੱਸ ਨਹੀਂ ਮਿਲੀ।',
    tryDifferentDate: 'ਦੂਜੀ ਮਿਤੀ ਚੁਣੋ।',

    seatsLeft: 'ਸੀਟਾਂ ਬਾਕੀ ਹਨ',
    compareFares: '6 ਐਪਸ ਦੇ ਕਿਰਾਏ ਦੇਖੋ',
    cheapestDeal: 'ਸਭ ਤੋਂ ਸਸਤੀ ਡੀਲ',
    bookOn: 'ਤੇ ਬੁੱਕ ਕਰੋ',
    bookTicket: 'ਸੀਟ ਚੁਣੋ ਅਤੇ ਬੁੱਕ ਕਰੋ',
    durationMins: 'ਘੰਟੇ',

    selectSeatTitle: 'ਸੀਟ ਅਤੇ ਯਾਤਰੀ ਦੇ ਵੇਰਵੇ',
    lowerBerth: 'ਹੇਠਲਾ ਡੈੱਕ',
    upperBerth: 'ਉਪਰਲਾ ਡੈੱਕ',
    selectedSeats: 'ਚੁਣੀਆਂ ਗਈਆਂ ਸੀਟਾਂ',
    passengerName: 'ਪੂਰਾ ਨਾਮ',
    passengerAge: 'ਉਮਰ',
    passengerGender: 'ਲਿੰਗ',
    mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    emailAddress: 'ਈਮੇਲ ਪਤਾ',
    paymentMethod: 'ਭੁਗਤਾਨ ਵਿਧੀ ਚੁਣੋ',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'ਕਰੈਡਿਟ / ਡੈਬਿਟ ਕਾਰਡ',
    netBanking: 'ਨੈੱਟ ਬੈਂਕਿੰਗ',
    baseFare: 'ਮੂਲ ਕਿਰਾਇਆ',
    gstTaxes: 'ਟੈਕਸ ਅਤੇ ਸੇਵਾ ਫੀਸ',
    totalPayable: 'ਕੁੱਲ ਭੁਗਤਾਨ ਯੋਗ ਰਕਮ',
    confirmPay: 'ਭੁਗਤਾਨ ਕਰੋ ਅਤੇ ਟਿਕਟ ਪੱਕੀ ਕਰੋ',
    ticketConfirmed: 'ਬੁਕਿੰਗ ਸਫਲ ਰਹੀ!',
    pnrNumber: 'PNR ਨੰਬਰ',
    downloadTicket: 'ਟਿਕਟ ਡਾਊਨਲੋਡ ਕਰੋ',

    footerRights: 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।',
  },

  or: {
    appName: 'ଯାତ୍ରା ସାଥୀ',
    tagline: 'ଭଏସ୍ ବସ୍ ଟିକେଟ୍ ସର୍ଚ୍ଚ',
    searchBuses: 'ବସ୍ ଖୋଜନ୍ତୁ',
    popularRoutes: 'ଲୋକପ୍ରିୟ ରୁଟ୍',
    home: 'ହୋମ୍',
    login: 'ଲଗଇନ୍',
    signup: 'ସାଇନ୍ ଅପ୍',
    admin: 'ଆଡମିନ୍',
    selectLanguage: 'ଭାଷା',
    
    heroBadge: '୬ଟି ଆପ୍ ର ଭଡା ତୁଳନା କରନ୍ତୁ',
    heroTitle1: 'ସବୁଠାରୁ କମ୍ ଦାମରେ ବସ୍ ଟିକେଟ୍,',
    heroTitle2: 'ପ୍ରତିଥର ପାଆନ୍ତୁ।',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip ଏବଂ Paytm Bus ଭଡା ତୁଳନା କରନ୍ତୁ।',
    noHiddenCharges: 'କୌଣସି ଲୁକ୍କାୟିତ ଚାର୍ଜ ନାହିଁ',
    instantResults: 'ତୁରନ୍ତ ଫଳାଫଳ',
    bestPrice: 'ସର୍ବୋତ୍ତମ ମୂଲ୍ୟ ଗ୍ୟାରେଣ୍ଟି',
    
    fromLabel: 'ଯାତ୍ରା ଆରମ୍ଭ ସହର (From)',
    toLabel: 'ଗନ୍ତବ୍ୟ ସହର (To)',
    dateLabel: 'ଯାତ୍ରା ତାରିଖ',
    selectOrigin: 'ଯାତ୍ରା ଆରମ୍ଭ ସହର ବାଛନ୍ତୁ',
    selectDestination: 'ଗନ୍ତବ୍ୟ ସହର ବାଛନ୍ତୁ',
    searchBtn: 'ବସ୍ ଖୋଜନ୍ତୁ',
    swapBtn: 'ବଦଳାନ୍ତୁ',
    
    popRoutesTitle: 'ଲୋକପ୍ରିୟ ବସ୍ ରୁଟ୍',
    popRoutesSub: 'ସବୁଠାରୁ ଅଧିକ ଖୋଜାଯାଇଥିବା ରୁଟ୍',
    viewAll: 'ସବୁ ଦେଖନ୍ତୁ',
    from: 'ରୁ',
    to: 'କୁ',
    startingFrom: 'ଆରମ୍ଭ ମୂଲ୍ୟ ₹',
    
    voiceTitle: 'ଭଏସ୍ ବସ୍ ସର୍ଚ୍ଚ',
    voiceHint: 'ମାଇକ୍ ଦବାନ୍ତୁ ଏବଂ ଯାତ୍ରା ବିଷୟରେ କୁହନ୍ତୁ',
    recording: 'ଶୁଣୁଛୁ... କୁହନ୍ତୁ',
    processing: 'ପ୍ରୋସେସିଂ ହେଉଛି...',
    stopRecording: 'ରଖିବାକୁ ଦବାନ୍ତୁ',
    speakNow: 'କହିବାକୁ ଦବାନ୍ତୁ',
    voiceLanguageLabel: 'ଭଏସ୍ ଭାଷା',

    resultsTitle: 'ବସ୍ ସର୍ଚ୍ଚ ଫଳାଫଳ',
    busesFound: 'ଟି ବସ୍ ମିଳିଲା',
    sortBy: 'ସଜାଡନ୍ତୁ',
    priceLowHigh: 'ଭଡା: କମ୍ ରୁ ଅଧିକ',
    priceHighLow: 'ଭଡା: ଅଧିକ ରୁ କମ୍',
    ratingHighLow: 'ରେଟିଂ: ଅଧିକ ରୁ କମ୍',
    departureTime: 'ଛାଡିବା ସମୟ',
    duration: 'ଯାତ୍ରା ସମୟ',
    filterTitle: 'ଫିଲ୍ଟର୍',
    busType: 'ବସ୍ ପ୍ରକାର',
    acStatus: 'AC ପ୍ରକାର',
    busModel: 'ବସ୍ ମଡେଲ୍',
    maxPriceLabel: 'ସର୍ବାଧିକ ଭଡା',
    minRatingLabel: 'ସର୍ବନିମ୍ନ ରେଟିଂ',
    allTypes: 'ସମସ୍ତ ପ୍ରକାର',
    sleeper: 'ସ୍ଲିପର୍',
    semiSleeper: 'ସେମି-ସ୍ଲିପର୍',
    seater: 'ସିଟର୍',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'ବୁକିଂ ଆପ୍',
    resetFilters: 'ରିସେଟ୍ କରନ୍ତୁ',
    noBuses: 'ଏହି ରୁଟ୍ ରେ କୌଣସି ବସ୍ ମିଳିଲା ନାହିଁ।',
    tryDifferentDate: 'ଅନ୍ୟ ତାରିଖ ବାଛନ୍ତୁ।',

    seatsLeft: 'ଟି ସିଟ୍ ଖାଲି ଅଛି',
    compareFares: '୬ଟି ଆପ୍ ର ଭଡା ତୁଳନା କରନ୍ତୁ',
    cheapestDeal: 'ସବୁଠାରୁ ଶସ୍ତା ଭଡା',
    bookOn: 'ରେ ବୁକ୍ କରନ୍ତୁ',
    bookTicket: 'ସିଟ୍ ବାଛି ବୁକ୍ କରନ୍ତୁ',
    durationMins: 'ଘଣ୍ଟା',

    selectSeatTitle: 'ସିଟ୍ ଏବଂ ଯାତ୍ରୀ ବିବରଣୀ',
    lowerBerth: 'ତଳ ଡେକ୍',
    upperBerth: 'ଉପର ଡେକ୍',
    selectedSeats: 'ବଛାଯାଇଥିବା ସିଟ୍',
    passengerName: 'ପୂରା ନାମ',
    passengerAge: 'ବୟସ',
    passengerGender: 'ଲିଙ୍ଗ',
    mobileNumber: 'ମୋବାଇଲ୍ ନମ୍ବର',
    emailAddress: 'ଇମେଲ୍ ଠିକଣା',
    paymentMethod: 'ପେମେଣ୍ଟ ଉପାୟ ବାଛନ୍ତୁ',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'କ୍ରେଡିଟ୍ / ଡେବିଟ୍ କାର୍ଡ',
    netBanking: 'ନେଟ୍ ବ୍ୟାଙ୍କିଂ',
    baseFare: 'ମୂଳ ଭଡା',
    gstTaxes: 'ଟିକସ ଏବଂ ସେବା ଫି',
    totalPayable: 'ମୋଟ ଦେୟ ମୂଲ୍ୟ',
    confirmPay: 'ପେମେଣ୍ଟ କରି ଟିକେଟ୍ କନଫର୍ମ କରନ୍ତୁ',
    ticketConfirmed: 'ବୁକିଂ ସଫଳ ହେଲା!',
    pnrNumber: 'PNR ନମ୍ବର',
    downloadTicket: 'ଟିକେଟ୍ ଡାଉନ୍‌ଲୋଡ୍ କରନ୍ତୁ',

    footerRights: 'ସମସ୍ତ ଅଧିକାର ସୁରକ୍ଷିତ।',
  },
};

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguageState] = useState<string>('en');

  const setLanguage = (code: string) => {
    if (SUPPORTED_LANGUAGES.some((l) => l.code === code)) {
      setCurrentLanguageState(code);
    }
  };

  const t = (key: string): string => {
    const langDict = translations[currentLanguage] || translations.en;
    return langDict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
