import { createContext, useContext, useState, ReactNode } from 'react';

export interface LanguageOption {
  code: string;
  name: string;
  native_name: string;
  voice_available: boolean;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', native_name: 'English', voice_available: true },
  { code: 'te', name: 'Telugu', native_name: 'తెలుగు', voice_available: true },
  { code: 'hi', name: 'Hindi', native_name: 'हिन्दी', voice_available: true },
  { code: 'ta', name: 'Tamil', native_name: 'தமிழ்', voice_available: true },
  { code: 'kn', name: 'Kannada', native_name: 'ಕನ್ನಡ', voice_available: true },
  { code: 'ml', name: 'Malayalam', native_name: 'മലയാളം', voice_available: true },
  { code: 'mr', name: 'Marathi', native_name: 'मराठी', voice_available: true },
  { code: 'gu', name: 'Gujarati', native_name: 'ગુજરાતી', voice_available: true },
  { code: 'bn', name: 'Bengali', native_name: 'বাংলা', voice_available: true },
  { code: 'ur', name: 'Urdu', native_name: 'اردو', voice_available: true },
  { code: 'pa', name: 'Punjabi', native_name: 'ਪੰਜਾਬੀ', voice_available: true },
  { code: 'or', name: 'Odia', native_name: 'ଓଡ଼ିଆ', voice_available: true },
];

type Translations = Record<string, Record<string, string>>;

const translations: Translations = {
  en: {
    appName: 'YatraSaathi',
    tagline: 'Voice-Enabled Bus Aggregator',
    searchBuses: 'Search Buses',
    popularRoutes: 'Popular Routes',
    home: 'Home',
    login: 'Login',
    signup: 'Sign Up',
    admin: 'Admin',
    selectLanguage: 'Language',
    
    // Hero
    heroBadge: 'Compare 6 OTAs in one search',
    heroTitle1: 'Find the cheapest bus ticket,',
    heroTitle2: 'every single time.',
    heroSubtitle: 'Compare fares across redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip, and Paytm Bus. One search, all options, best price guaranteed.',
    noHiddenCharges: 'No hidden charges',
    instantResults: 'Instant results',
    bestPrice: 'Best price from 6 OTAs',
    
    // Search Form
    fromLabel: 'From / Departure City',
    toLabel: 'To / Destination City',
    dateLabel: 'Travel Date',
    selectOrigin: 'Select origin city',
    selectDestination: 'Select destination city',
    searchBtn: 'Search Buses',
    swapBtn: 'Swap cities',
    
    // Popular Routes
    popRoutesTitle: 'Popular Bus Routes',
    popRoutesSub: 'Most searched bus routes across top Indian cities',
    viewAll: 'View all',
    from: 'From',
    to: 'to',
    startingFrom: 'From ₹',
    
    // Voice Bar
    voiceTitle: 'Voice Bus Search',
    voiceHint: 'Tap the mic & speak your route in your preferred language (e.g., "buses from Hyderabad to Vijayawada tomorrow")',
    recording: 'Listening... Speak your journey details',
    processing: 'Processing your voice request...',
    stopRecording: 'Tap to Stop',
    speakNow: 'Tap to Speak',
    voiceLanguageLabel: 'Voice Language',

    // Results Page
    resultsTitle: 'Bus Search Results',
    busesFound: 'buses found',
    sortBy: 'Sort by',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    ratingHighLow: 'Rating: High to Low',
    departureTime: 'Departure Time',
    duration: 'Duration',
    filterTitle: 'Filter Buses',
    busType: 'Bus Type',
    acStatus: 'AC Type',
    busModel: 'Bus Model',
    maxPriceLabel: 'Max Price',
    minRatingLabel: 'Min Rating',
    allTypes: 'All Types',
    sleeper: 'Sleeper',
    semiSleeper: 'Semi-Sleeper',
    seater: 'Seater',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'Booking Platforms',
    resetFilters: 'Reset Filters',
    noBuses: 'No bus listings found for this route.',
    tryDifferentDate: 'Try changing dates or selecting another city pair.',

    // Bus Card & Booking
    seatsLeft: 'seats left',
    compareFares: 'Compare Fares Across 6 OTAs',
    cheapestDeal: 'Cheapest Deal',
    bookOn: 'Book on',
    bookTicket: 'Book Ticket & Select Seat',
    durationMins: 'hrs',

    // Booking Modal
    selectSeatTitle: 'Select Seats & Passenger Details',
    lowerBerth: 'Lower Deck',
    upperBerth: 'Upper Deck',
    selectedSeats: 'Selected Seats',
    passengerName: 'Full Name',
    passengerAge: 'Age',
    passengerGender: 'Gender',
    mobileNumber: 'Mobile Number',
    emailAddress: 'Email Address',
    paymentMethod: 'Select Payment Method',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'Credit / Debit Card',
    netBanking: 'Net Banking',
    baseFare: 'Base Fare',
    gstTaxes: 'Taxes & Service Fee',
    totalPayable: 'Total Amount Payable',
    confirmPay: 'Pay & Confirm Ticket',
    ticketConfirmed: 'Booking Confirmed!',
    pnrNumber: 'PNR Number',
    downloadTicket: 'Download Ticket',

    // Footer
    footerRights: 'All rights reserved. India’s multi-lingual smart bus tickets aggregator.',
  },

  te: {
    appName: 'యాత్రా సాథి',
    tagline: 'వాయిస్ సపోర్ట్‌తో బస్సు టికెట్లు',
    searchBuses: 'బస్సులను వెతకండి',
    popularRoutes: 'పాపులర్ మార్గాలు',
    home: 'హోమ్',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    admin: 'అడ్మిన్',
    selectLanguage: 'భాష',
    
    heroBadge: 'ఒకే శోధనలో 6 యాప్‌ల ధరల పోలిక',
    heroTitle1: 'అతి తక్కువ ధరకే బస్సు టికెట్,',
    heroTitle2: 'ప్రతిసారీ పొందండి.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip మరియు Paytm Bus ల ధరలను పోల్చండి.',
    noHiddenCharges: 'హిడెన్ ఛార్జీలు లేవు',
    instantResults: 'వెంటనే ఫలితాలు',
    bestPrice: '6 యాప్‌ల నుండి ఉత్తమ ధర',
    
    fromLabel: 'బయలుదేరే నగరం (From)',
    toLabel: 'చేరుకునే నగరం (To)',
    dateLabel: 'ప్రయాణ తేదీ',
    selectOrigin: 'బయలుదేరే నగరాన్ని ఎంచుకోండి',
    selectDestination: 'చేరుకునే నగరాన్ని ఎంచుకోండి',
    searchBtn: 'బస్సులను వెతకండి',
    swapBtn: 'నగరాలను మార్చండి',
    
    popRoutesTitle: 'పాపులర్ బస్సు రూట్లు',
    popRoutesSub: 'అత్యధికంగా శోధించిన బస్సు మార్గాలు',
    viewAll: 'అన్నీ చూడండి',
    from: 'నుండి',
    to: 'కి',
    startingFrom: 'ప్రారంభ ధర ₹',
    
    voiceTitle: 'వాయిస్ బస్సు సెర్చ్',
    voiceHint: 'మైక్ నొక్కి మీరు వెళ్లాల్సిన ఊరు గురించి మాట్లాడండి (ఉదా: "రేపు వైజాగ్ నుండి హైదరాబాద్ బస్సులు")',
    recording: 'వింటున్నాము... మీ ప్రయాణ వివరాలు చెప్పండి',
    processing: 'మీ వాయిస్ ప్రాసెస్ అవుతోంది...',
    stopRecording: 'ఆపడానికి నొక్కండి',
    speakNow: 'మాట్లాడటానికి మైక్ నొక్కండి',
    voiceLanguageLabel: 'వాయిస్ భాష',

    resultsTitle: 'బస్సు శోధన ఫలితాలు',
    busesFound: 'బస్సులు అందుబాటులో ఉన్నాయి',
    sortBy: 'వరుస క్రమం',
    priceLowHigh: 'ధర: తక్కువ నుండి ఎక్కువ',
    priceHighLow: 'ధర: ఎక్కువ నుండి తక్కువ',
    ratingHighLow: 'రేటింగ్: ఎక్కువ నుండి తక్కువ',
    departureTime: 'బయలుదేరే సమయం',
    duration: 'ప్రయాణ సమయం',
    filterTitle: 'ఫిల్టర్లు',
    busType: 'బస్సు రకం',
    acStatus: 'AC రకం',
    busModel: 'బస్సు మోడల్',
    maxPriceLabel: 'గరిష్ట ధర',
    minRatingLabel: 'కనిష్ట రేటింగ్',
    allTypes: 'అన్ని రకాలు',
    sleeper: 'స్లీపర్',
    semiSleeper: 'సెమీ-స్లీపర్',
    seater: 'సీటర్',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'బుకింగ్ యాప్‌లు',
    resetFilters: 'ఫిల్టర్లు రీసెట్ చేయండి',
    noBuses: 'ఈ రూట్‌లో బస్సులు కనిపించలేదు.',
    tryDifferentDate: 'వేరే తేదీ లేదా నగరాన్ని ఎంచుకోండి.',

    seatsLeft: 'సీట్లు ఉన్నాయి',
    compareFares: '6 యాప్‌లలో ధరలు చూడండి',
    cheapestDeal: 'అత్యంత తక్కువ ధర',
    bookOn: 'బుక్ చేయండి',
    bookTicket: 'సీటు ఎంచుకుని బుక్ చేయండి',
    durationMins: 'గంటలు',

    selectSeatTitle: 'సీట్లు మరియు ప్రయాణీకుల వివరాలు',
    lowerBerth: 'కింది డెక్',
    upperBerth: 'పై డెక్',
    selectedSeats: 'ఎంచుకున్న సీట్లు',
    passengerName: 'పూర్తి పేరు',
    passengerAge: 'వయస్సు',
    passengerGender: 'లింగం',
    mobileNumber: 'ఫోన్ నంబర్',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    paymentMethod: 'చెల్లింపు విధానం ఎంచుకోండి',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'క్రెడిట్ / డెబిట్ కార్డ్',
    netBanking: 'నెట్ బ్యాంకింగ్',
    baseFare: 'మూల ధర',
    gstTaxes: 'పన్నులు & సేవా రుసుము',
    totalPayable: 'మొత్తం చెల్లించాల్సిన మొత్తం',
    confirmPay: 'చెల్లించి టికెట్ ఖరారు చేయండి',
    ticketConfirmed: 'బుకింగ్ విజయవంతమైంది!',
    pnrNumber: 'PNR నంబర్',
    downloadTicket: 'టికెట్ డౌన్‌లోడ్ చేయండి',

    footerRights: 'అన్ని హక్కులు ప్రత్యేకించబడ్డాయి. భారతదేశపు మల్టీలింగువల్ బస్సు టికెట్ యాప్.',
  },

  hi: {
    appName: 'यात्रा साथी',
    tagline: 'वॉयस-सक्षम बस टिकट खोजें',
    searchBuses: 'बसें खोजें',
    popularRoutes: 'लोकप्रिय मार्ग',
    home: 'होम',
    login: 'लॉग इन',
    signup: 'साइन अप',
    admin: 'एडमिन',
    selectLanguage: 'भाषा',
    
    heroBadge: 'एक ही खोज में 6 ऐप्स के किराए की तुलना करें',
    heroTitle1: 'पाएं सबसे सस्ती बस टिकट,',
    heroTitle2: 'हर एक बार।',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip और Paytm Bus के किरायों की तुलना करें।',
    noHiddenCharges: 'कोई छिपा हुआ शुल्क नहीं',
    instantResults: 'तुरंत परिणाम',
    bestPrice: '6 ऐप्स से सबसे कम कीमत',
    
    fromLabel: 'प्रस्थान शहर (From)',
    toLabel: 'गंतव्य शहर (To)',
    dateLabel: 'यात्रा तिथि',
    selectOrigin: 'प्रस्थान शहर चुनें',
    selectDestination: 'गंतव्य शहर चुनें',
    searchBtn: 'बसें खोजें',
    swapBtn: 'शहर बदलें',
    
    popRoutesTitle: 'लोकप्रिय बस मार्ग',
    popRoutesSub: 'प्रमुख भारतीय शहरों के बीच सबसे अधिक खोजे गए मार्ग',
    viewAll: 'सभी देखें',
    from: 'से',
    to: 'तक',
    startingFrom: 'शुरुआती किराया ₹',
    
    voiceTitle: 'वॉयस बस खोज',
    voiceHint: 'माइक दबाएं और अपनी यात्रा बोलें (जैसे: "कल दिल्ली से जयपुर की बसें")',
    recording: 'सुन रहे हैं... अपनी यात्रा का विवरण बोलें',
    processing: 'आपकी आवाज को संसाधित किया जा रहा है...',
    stopRecording: 'रोकने के लिए दबाएं',
    speakNow: 'बोलने के लिए माइक दबाएं',
    voiceLanguageLabel: 'वॉयस भाषा',

    resultsTitle: 'बस खोज परिणाम',
    busesFound: 'बसें उपलब्ध हैं',
    sortBy: 'क्रमबद्ध करें',
    priceLowHigh: 'किराया: कम से अधिक',
    priceHighLow: 'किराया: अधिक से कम',
    ratingHighLow: 'रेटिंग: अधिक से कम',
    departureTime: 'प्रस्थान समय',
    duration: 'समय',
    filterTitle: 'फिल्टर',
    busType: 'बस का प्रकार',
    acStatus: 'एसी प्रकार',
    busModel: 'बस मॉडल',
    maxPriceLabel: 'अधिकतम किराया',
    minRatingLabel: 'न्यूनतम रेटिंग',
    allTypes: 'सभी प्रकार',
    sleeper: 'स्लीपर',
    semiSleeper: 'सेमी-स्लीपर',
    seater: 'सीटर',
    ac: 'AC',
    nonAc: 'नॉन-AC',
    otaFilter: 'बुकिंग प्लेटफॉर्म',
    resetFilters: 'फ़िल्टर रीसेट करें',
    noBuses: 'इस मार्ग के लिए कोई बस नहीं मिली।',
    tryDifferentDate: 'कृपया दूसरी तिथि या शहर चुनें।',

    seatsLeft: 'सीटें बची हैं',
    compareFares: '6 ऐप्स के किरायों की तुलना करें',
    cheapestDeal: 'सबसे सस्ता विकल्प',
    bookOn: 'बुक करें',
    bookTicket: 'सीट चुनें और बुक करें',
    durationMins: 'घंटे',

    selectSeatTitle: 'सीट और यात्री विवरण चुनें',
    lowerBerth: 'निचला डेक',
    upperBerth: 'ऊपरी डेक',
    selectedSeats: 'चुनी गई सीटें',
    passengerName: 'पूरा नाम',
    passengerAge: 'आयु',
    passengerGender: 'लिंग',
    mobileNumber: 'मोबाइल नंबर',
    emailAddress: 'ईमेल पता',
    paymentMethod: 'भुगतान विधि चुनें',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'क्रेडिट / डेबिट कार्ड',
    netBanking: 'नेट बैंकिंग',
    baseFare: 'मूल किराया',
    gstTaxes: 'कर और सेवा शुल्क',
    totalPayable: 'कुल देय राशि',
    confirmPay: 'भुगतान करें और टिकट कन्फर्म करें',
    ticketConfirmed: 'बुकिंग सफल रही!',
    pnrNumber: 'पीएनआर नंबर',
    downloadTicket: 'टिकट डाउनलोड करें',

    footerRights: 'सर्वाधिकार सुरक्षित। भारत का बहुभाषी स्मार्ट बस टिकट एग्रीगेटर।',
  },

  ta: {
    appName: 'யாத்ரா சாதி',
    tagline: 'குரல் வழி பேருந்து தேடல்',
    searchBuses: 'பேருந்துகளைத் தேடுங்கள்',
    popularRoutes: 'பிரபலமான பாதைகள்',
    home: 'முகப்பு',
    login: 'லாகின்',
    signup: 'சைன் அப்',
    admin: 'அட்மின்',
    selectLanguage: 'மொழி',
    
    heroBadge: '6 செயலிகளின் கட்டணங்களை ஒப்பிடுங்கள்',
    heroTitle1: 'மிகக் குறைந்த விலையில் பேருந்து டிக்கெட்,',
    heroTitle2: 'ஒவ்வொரு முறையும்.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip மற்றும் Paytm Bus கட்டணங்களை ஒப்பிடுங்கள்.',
    noHiddenCharges: 'மறைமுகக் கட்டணங்கள் இல்லை',
    instantResults: 'உடனடி முடிவுகள்',
    bestPrice: '6 செயலிகளில் சிறந்த விலை',
    
    fromLabel: 'புறப்படும் நகரம் (From)',
    toLabel: 'சென்றடையும் நகரம் (To)',
    dateLabel: 'பயண தேதி',
    selectOrigin: 'புறப்படும் நகரத்தை தேர்ந்தெடுக்கவும்',
    selectDestination: 'சென்றடையும் நகரத்தை தேர்ந்தெடுக்கவும்',
    searchBtn: 'பேருந்துகளைத் தேடுங்கள்',
    swapBtn: 'நகரங்களை மாற்றுக',
    
    popRoutesTitle: 'பிரபலமான பேருந்து பாதைகள்',
    popRoutesSub: 'அதிகம் தேடப்பட்ட பேருந்து பாதைகள்',
    viewAll: 'அனைத்தையும் காண்க',
    from: 'இருந்து',
    to: 'வரை',
    startingFrom: 'ஆரம்ப விலை ₹',
    
    voiceTitle: 'குரல் வழி பேருந்து தேடல்',
    voiceHint: 'மைக்கை அழுத்தி உங்கள் பயண விவரங்களை பேசுங்கள்',
    recording: 'கேட்கிறது... பேசுங்கள்',
    processing: 'செயலாக்கப்படுகிறது...',
    stopRecording: 'நிறுத்த அழுத்தவும்',
    speakNow: 'பேச மைக்கை அழுத்தவும்',
    voiceLanguageLabel: 'குரல் மொழி',

    resultsTitle: 'பேருந்து தேடல் முடிவுகள்',
    busesFound: 'பேருந்துகள் உள்ளன',
    sortBy: 'வரிசைப்படுத்து',
    priceLowHigh: 'விலை: குறைந்ததிலிருந்து அதிகம்',
    priceHighLow: 'விலை: அதிகத்திலிருந்து குறைவு',
    ratingHighLow: 'ரேட்டிங்: அதிகத்திலிருந்து குறைவு',
    departureTime: 'புறப்படும் நேரம்',
    duration: 'பயண நேரம்',
    filterTitle: 'வடிகட்டிகள்',
    busType: 'பேருந்து வகை',
    acStatus: 'ஏசி வகை',
    busModel: 'பேருந்து மாடல்',
    maxPriceLabel: 'அதிகபட்ச விலை',
    minRatingLabel: 'குறைந்தபட்ச ரேட்டிங்',
    allTypes: 'அனைத்து வகைகள்',
    sleeper: 'ஸ்லீப்பர்',
    semiSleeper: 'செமி-ஸ்லீப்பர்',
    seater: 'சீட்டர்',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'புக்கிங் செயலிகள்',
    resetFilters: 'மீட்டமைக்க',
    noBuses: 'இந்த பாதையில் பேருந்துகள் இல்லை.',
    tryDifferentDate: 'வேறு தேதியை தேர்ந்தெடுக்கவும்.',

    seatsLeft: 'இருக்கைகள் உள்ளன',
    compareFares: '6 செயலிகளின் கட்டணங்களை ஒப்பிடுக',
    cheapestDeal: 'மிகக் குறைந்த விலை',
    bookOn: 'முன்பதிவு செய்ய',
    bookTicket: 'இருக்கை தேர்வு செய்து முன்பதிவு செய்க',
    durationMins: 'மணிநேரம்',

    selectSeatTitle: 'இருக்கை மற்றும் பயணி விவரங்கள்',
    lowerBerth: 'கீழ் தளம்',
    upperBerth: 'மேல் தளம்',
    selectedSeats: 'தேர்ந்தெடுக்கப்பட்ட இருக்கைகள்',
    passengerName: 'முழு பெயர்',
    passengerAge: 'வயது',
    passengerGender: 'பாலினம்',
    mobileNumber: 'மொபைல் எண்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    paymentMethod: 'பணம் செலுத்தும் முறை',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'கிரெடிட் / டெபிட் கார்டு',
    netBanking: 'நெட் பேங்கிங்',
    baseFare: 'அடிப்படை கட்டணம்',
    gstTaxes: 'வரிகள் & સેવાக் கட்டணம்',
    totalPayable: 'மொத்தம் செலுத்த வேண்டியது',
    confirmPay: 'பணம் செலுத்தி உறுதி செய்க',
    ticketConfirmed: 'முன்பதிவு உறுதி செய்யப்பட்டது!',
    pnrNumber: 'PNR எண்',
    downloadTicket: 'டிக்கெட் பதிவிறக்கவும்',

    footerRights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
  },

  kn: {
    appName: 'ಯಾತ್ರಾ ಸಾಥಿ',
    tagline: 'ವಾಯ್ಸ್ ಮೂಲಕ ಬಸ್ ಟಿಕೆಟ್ ಹುಡುಕಾಟ',
    searchBuses: 'ಬಸ್‌ಗಳನ್ನು ಹುಡುಕಿ',
    popularRoutes: 'ಜನಪ್ರಿಯ ಮಾರ್ಗಗಳು',
    home: 'ಹೋಮ್',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    admin: 'ಅಡ್ಮಿನ್',
    selectLanguage: 'ಭಾಷೆ',
    
    heroBadge: '6 ಆಪ್‌ಗಳಲ್ಲಿ ದರಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ',
    heroTitle1: 'ಅತಿ ಕಡಿಮೆ ದರದಲ್ಲಿ ಬಸ್ ಟಿಕೆಟ್,',
    heroTitle2: 'ಪ್ರತಿ ಬಾರಿಯೂ ಪಡೆಯಿರಿ.',
    heroSubtitle: 'redBus, MakeMyTrip, AbhiBus, TravelYaari, EaseMyTrip ಮತ್ತು Paytm Bus ದರಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ.',
    noHiddenCharges: 'ಯಾವುದೇ ಗುಪ್ತ ಶುಲ್ಕವಿಲ್ಲ',
    instantResults: 'ತಕ್ಷಣದ ಫಲಿತಾಂಶಗಳು',
    bestPrice: 'ಉತ್ತಮ ಬೆಲೆ ಖಾತರಿ',
    
    fromLabel: 'ಹೊರಡುವ ನಗರ (From)',
    toLabel: 'ತಲುಪುವ ನಗರ (To)',
    dateLabel: 'ಪ್ರಯಾಣದ ದಿನಾಂಕ',
    selectOrigin: 'ಹೊರಡುವ ನಗರ ಆಯ್ಕೆಮಾಡಿ',
    selectDestination: 'ತಲುಪುವ ನಗರ ಆಯ್ಕೆಮಾಡಿ',
    searchBtn: 'ಬಸ್‌ಗಳನ್ನು ಹುಡುಕಿ',
    swapBtn: 'ನಗರಗಳನ್ನು ಬದಲಾಯಿಸಿ',
    
    popRoutesTitle: 'ಜನಪ್ರಿಯ ಬಸ್ ಮಾರ್ಗಗಳು',
    popRoutesSub: 'ಹೆಚ್ಚು ಹುಡುಕಲ್ಪಟ್ಟ ಬಸ್ ಮಾರ್ಗಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    from: 'ಇಂದ',
    to: 'ಗೆ',
    startingFrom: 'ಆರಂಭಿಕ ದರ ₹',
    
    voiceTitle: 'ವಾಯ್ಸ್ ಬಸ್ ಶೋಧನೆ',
    voiceHint: 'ಮೈಕ್ ಒತ್ತಿ ನಿಮ್ಮ ಪ್ರಯಾಣದ ವಿವರಗಳನ್ನು ಮಾತನಾಡಿ',
    recording: 'ಆಲಿಸಲಾಗುತ್ತಿದೆ... ಮಾತನಾಡಿ',
    processing: 'ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ...',
    stopRecording: 'ನಿಲ್ಲಿಸಲು ಒತ್ತಿ',
    speakNow: 'ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿ',
    voiceLanguageLabel: 'ವಾಯ್ಸ್ ಭಾಷೆ',

    resultsTitle: 'ಬಸ್ ಹುಡುಕಾಟದ ಫಲಿತಾಂಶಗಳು',
    busesFound: 'ಬಸ್‌ಗಳು ಲಭ್ಯವಿವೆ',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    priceLowHigh: 'ದರ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚು',
    priceHighLow: 'ದರ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆ',
    ratingHighLow: 'ರೇಟಿಂಗ್: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆ',
    departureTime: 'ಹೊರಡುವ ಸಮಯ',
    duration: 'ಪ್ರಯಾಣ ಸಮಯ',
    filterTitle: 'ಫಿಲ್ಟರ್‌ಗಳು',
    busType: 'ಬಸ್ ಮಾದರಿ',
    acStatus: 'AC ಮಾದರಿ',
    busModel: 'ಬಸ್ ಮಾಡೆಲ್',
    maxPriceLabel: 'ಗರಿಷ್ಠ ದರ',
    minRatingLabel: 'ಕನಿಷ್ಠ ರೇಟಿಂಗ್',
    allTypes: 'ಎಲ್ಲಾ ಮಾದರಿಗಳು',
    sleeper: 'ಸ್ಲೀಪರ್',
    semiSleeper: 'ಸೆಮಿ-ಸ್ಲೀಪರ್',
    seater: 'ಸೀಟರ್',
    ac: 'AC',
    nonAc: 'Non-AC',
    otaFilter: 'ಬುಕಿಂಗ್ ಆಪ್‌ಗಳು',
    resetFilters: 'ಮರುಹೊಂದಿಸಿ',
    noBuses: 'ಈ ಮಾರ್ಗದಲ್ಲಿ ಬಸ್‌ಗಳು ಸಿಗಲಿಲ್ಲ.',
    tryDifferentDate: 'ಮತ್ತೊಂದು ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ.',

    seatsLeft: 'ಸೀಟುಗಳು ಲಭ್ಯವಿವೆ',
    compareFares: '6 ಆಪ್‌ಗಳ ದರಗಳನ್ನು ಹೋಲಿಸಿ',
    cheapestDeal: 'ಅತಿ ಅಗ್ಗದ ದರ',
    bookOn: 'ಬುಕ್ ಮಾಡಿ',
    bookTicket: 'ಸೀಟು ಆಯ್ಕೆಮಾಡಿ ಬುಕ್ ಮಾಡಿ',
    durationMins: 'ಗಂಟೆಗಳು',

    selectSeatTitle: 'ಸೀಟು ಮತ್ತು ಪ್ರಯಾಣಿಕರ ವಿವರಗಳು',
    lowerBerth: 'ಕೆಳಗಿನ ಡೆಕ್',
    upperBerth: 'ಮೇಲಿನ ಡೆಕ್',
    selectedSeats: 'ಆಯ್ಕೆಮಾಡಿದ ಸೀಟುಗಳು',
    passengerName: 'ಪೂರ್ಣ ಹೆಸರು',
    passengerAge: 'ವಯಸ್ಸು',
    passengerGender: 'ಲಿಂಗ',
    mobileNumber: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    paymentMethod: 'ಪಾವತಿ ವಿಧಾನ ಆಯ್ಕೆಮಾಡಿ',
    upiPay: 'UPI / GPay / PhonePe / Paytm',
    cardPay: 'ಕ್ರೆಡಿಟ್ / ಡೆಬಿಟ್ ಕಾರ್ಡ್',
    netBanking: 'ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್',
    baseFare: 'ಮೂಲ ದರ',
    gstTaxes: 'ತೆರಿಗೆಗಳು ಮತ್ತು ಸೇವಾ ಶುಲ್ಕ',
    totalPayable: 'ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ',
    confirmPay: 'ಪಾವತಿಸಿ ಟಿಕೆಟ್ ಖಚಿತಪಡಿಸಿ',
    ticketConfirmed: 'ಬುಕಿಂಗ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
    pnrNumber: 'PNR ಸಂಖ್ಯೆ',
    downloadTicket: 'ಟಿಕೆಟ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',

    footerRights: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
  },
};

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguageState] = useState<string>('en');

  const setLanguage = (code: string) => {
    if (SUPPORTED_LANGUAGES.some((l) => l.code === code)) {
      setCurrentLanguageState(code);
    }
  };

  const t = (key: string): string => {
    const langDict = translations[currentLanguage] || translations.en;
    return langDict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
